services:
  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    volumes:
      - mailpit:/data
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_DATABASE: /data/mailpit.db

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${PLANNER_DATABASE_NAME}
      POSTGRES_USER: ${PLANNER_DATABASE_USER}
      POSTGRES_PASSWORD: ${PLANNER_DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      PLANNER_DATABASE_NAME: ${PLANNER_DATABASE_NAME}
      PLANNER_DATABASE_USER: ${PLANNER_DATABASE_USER}
      PLANNER_DATABASE_PASSWORD: ${PLANNER_DATABASE_PASSWORD}
      PLANNER_DATABASE_PORT: ${PLANNER_DATABASE_PORT:-5432}
      PLANNER_DATABASE_HOST: ${PLANNER_DATABASE_HOST_DOCKER:-db}
    depends_on:
      - db

volumes:
  db_data:
    driver: local
  mailpit:
    driver: local